sudo: false
language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
install:
  - pip install -r requirements.txt
  - pip install "ltd-conveyor>=0.4.2,<0.5"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd upload --travis --dir _build/html --product dmtn-125
env:
  global:
    -
      # LTD_AWS_ID
      secure: pYOyO5iq/7MDHjOjStruABhD+Y8FBBzHe4Hu6OTf0CAhWuKjd+J+XQjPF935DeX6z9dNQsax89jtfpZ5i43ffdqjeYMjrNu/u2rYz1WCwlpMG3DApdeMe80+wRwNfAdHkZdKcuMJqrvInpfQ0Yr4h2hwRl9gMQw0xHMQnmDhV+10vRs9QJz6PcrgQT6K/ppf2OyrU+OKmz9nmQf8iZEmeNZDz1HdDxHv9kXl1Td3U96fHBF8XrkteP0nFXJiH/SmzmaL2YBw74O3RbL4RaxB2T3SoUR2gRr/Ot6LQihhDm+MyvTfxYdk7HDcjJX+rSaYI60HcyW62vziv60TJbzpW6wCqxK/PXReCyrFKcSxyEjhd4yGE0skNyHS/xyThNeKjEGOIZgPSzmcdoH/GHKpkLgJiXSZRohufd7bBy4RTzN+jlm5JrKMop1mtQkfWQ77elMaQaVjsvXswwl6wZobyDKHfIBLgB55IGMI7NKb5bVsd5SylyXgfAJG1U6jTNWjP0Dz46vhR8lUqQP1McJYrf0dk1HqiCIJMxyjH31K+hy1GCfWvueZ10LKYqmmOE/HnmamoNqg10HulvNh2h6vaGmf/FWFlQZtuJaE/up7hCwJ4K4EbvDgKNCTvCx7WfZ7t+fn3Wp/0twYUuNSeK7t83aLh5w11TBP34PJLLulWPY=
    -
      # LTD_AWS_SECRET
      secure: AEGtpBi3+DOVwZhzOWPAQgm0ED5Zt5PdAPuHlk4Uomd5U/rYwUTxw4WZQHHMCP+NRnwua5vVLpU60LIvYeA5/fa308JrRJLZmSrxCwH2Hj4NjIwunHp6qlKE87ib7aScT1Nt2utHnqqh7rILlHNNHjf6VRF05xwKlrLkydlBda27u7AX9XEbfCIoz0+I05re3HQ6P9XRUrGSAIDaXRgVrCvTRt+/rpq7kFKJr34Eq4/jiz+orDfstlekFZzAj2YqWhKCiIke/SrRcMvy/SyspiABU4hZW5/U5FRYrIXC6EuZsQNEY1IL7K2m82q9eY7c9zsdOWA+FtLrDekZC0iQjh3211J9gSYDhVl8WfbRi5Y4NIVI1OgqZTeFhfKiFs7qI6KJoCClAg0LSzZIzV+vzYCPg2zTE548imfhyYqYxJDRfgHc4ArheBFo/F+TjV95b6CKDIO/xHm5XU+MEdjz17XMs1+kk7kK1G/qubWt6a0h+x1BeU2xHYRcS7f0lPmeqCqp6zHXFIsgK0wTx2wkg2mV1yBmp1QqbLlDu/lYvSSXmC05dDaIAWExFffYKaMkobdZNTZx0oO3BH5ja2IVeHvhOtGIzz9N+XBR/3RZjRNR36nMgee4TiJBcR9irSKZQcxDIgMVWOAtzV+h6oMz0Tm2j68uijndhEyJEZSXGEk=
    -
      # LTD_USERNAME
      secure: eRxOBz/9w/uA6nq3Zc0Rgdr24DCvGGFj5XdPPBRjD7mBb4uC/g58+9mu9IQxT4aUbXWqo5JlRm4NNSWsfpDrtmd11OMRdHMUoOpdB6XEwfPoEMi57pY6kj917vjHI8mST4f3dy/+lqfzXbGoXXwzkAJ7uQfZWBOo5OtapzijJd5lLUyBuKYrE+z5J3AnYIE2fSVvL0A4c7K6GtsVq1dQV+gsjfofRLmiPdX3XdtMtIwu0MeXZIQYt4IqnoIUL1mTRKCtl2mZ1L9Td4waaZ7sS7vh0TUeyvGFGX73bNLeeERUtoqoSWf8Q+827Pfm4YGHpojSOyH6SGu+7SNbBqwT1p65l6B3JGTFFWHEpHzZJ9XZzN0m9VGC6sHBzMd5g0gMIZ1EoWEZLKIc14F4PhVkwRaQx5c7FcapIlIpU+sT+lXcBGcs8Km43xkfKb3V+zHip5jlKim+zjas1co/txFvlR6NuqRg9RlTh2IR1h/d76HFCxRv39ddGfDLjD5f+mi6zzOlCV9OwZlUxI5mF6GuVT89hAfxp8l84YHPC7Qjrcq1qS6/+LveIeXcHXWnCVxK5XWutq/Xa9kz9KLwVtMeYAPxGWZ1NFksVF7g249YqaHxrweUtcCOUVbaH0J+mr8jIbl8LVpw6CJ5sNhf9lGxzw0R1f9DR9cDkNHmvAPPVqE=
    -
      # LTD_PASSWORD
      secure: jIuRGFmhIxaS7PyT77SFfxz5rfO3VS246tOvsHLXjfhNFHQPNJnMkvs9sGLu5VKw3ycDEbM0X553TSkzK8iFRWnFjhck0xqE8U1Z5jHeNxWMCI6PolP3qvQ7KkXmLnpdKHI1gaPZaXN+eKAgtTS4f5UYBu3GESvTVTNsQ4YePsg2wjmhV39U8tRwhZ8/PQQ8wfc2Ru8zir1LN10K3ymBlXYyABlErc8kOwOwI8dMjivfZBnS5BH0INVBAO3xWDZ4PKcxNtnYKazvwOcLT0d5c7cI/YX8g9tyCDqTB0QZIqSczPkhoUv8t1jGDws1cZFnIFu5p13q9NEfLnrjmmVC8Q3+awhQEQIt26ws1fQ1x+fkFOCiOqC56hxZVBxfXOTHCvAMbGF6DdsdO6Z0rBd3kUpceq6GCNiBfPxcF9pb0E38rteKKOoBws4WEnBYpV4VdPRHpflI0Tjp4F5hy9qc03CCVaI8yD+I8KEs5BOR7M+INSOf+3BcT9Zv3Rei7x2uo7P+lf1VcBPLPujjHojWZVbQKuPhoHi+fhjZBBpKC/JQ09njdHf2Z4p+3eBkl7EjU3xclhRuUk4mvSsPzc5qeZZmYwK2pQ4zYMhByT53UAC/cV3bV8i7CcdqilCR8QJXNq8y7rCmhboZNWOz87vtGXKfRnqz/W10V3FzjjfE0T0=
